extends Node

var current_lang = "es"
var text_vars = []

var TEXTS = {
	"ui_start_es":"Comenzar",
	"ui_start_en": "Start",
	"ui_languaje_es":"Idioma",
	"ui_languaje_en": "Language",
	"ui_reset_data_es":"Borrar Datos",
	"ui_reset_data_en": "Reset Data",
	"ui_reset_data_sure_es":"Seguro?",
	"ui_reset_data_sure_en": "Are you sure?",
	"ui_continue_es":"Continuar",
	"ui_continue_en": "Continue",
	"ui_uses_es":" usos",
	"ui_uses_en":" charges",
	"ui_req_es":"costo",
	"ui_req_en":"cost",
	"ui_expedition_es":"Expedicion",
	"ui_expedition_en":"Expedition",
	"ui_prestige_es":"Prestigio",
	"ui_prestige_en":"Prestige",
	
	"ab_streng_name_es": "FUERZA BRUTA",
	"ab_streng_name_en": "BRUTE FORCE",
	"ab_streng_es": "Aumenta en +3 un dado de @STR",
	"ab_streng_en": "Increase one @STR die by +3",
	"ab_subtlety_name_es": "SUTILEZA",
	"ab_subtlety_name_en": "SUBTLETY",
	"ab_subtlety_es": "Aumenta +3 a un dado de @DEX",
	"ab_subtlety_en": "Increase one @DEX die by +3",
	"ab_atletic_name_es": "ATLETISMO",
	"ab_atletic_name_en": "ATHLETICS",
	"ab_atletic_es": "Cambia un dado @STR->@DEX o @DEX->@STR y suma +2",
	"ab_atletic_en": "Swap one die @STR↔@DEX and add +2",
	"ab_protector_name_es": "PROTECTOR",
	"ab_protector_name_en": "PROTECTOR",
	"ab_protector_es": "Obtienes 4 de escudo.",
	"ab_protector_en": "Gain 4 shield.",
	"ab_bendition_name_es": "BENDICION",
	"ab_bendition_name_en": "BLESSING",
	"ab_bendition_es": "Aumenta +2 a un dado al azar (debes tener al menos dos dados)",
	"ab_bendition_en": "Increase a random die by +2 (you must have at least two dice)",
	
	"ab_old_axe_name_es": "VIEJA HACHA",
	"ab_old_axe_name_en": "OLD AXE",
	"ab_old_axe_es": "Bonifica entre 1 y 6 el valor de un dado de @STR.",
	"ab_old_axe_en": "Boost a @STR die by 1 to 6.",
	"ab_sword_name_es": "GRAN ESPADA",
	"ab_sword_name_en": "GREAT SWORD",
	"ab_sword_es": "Lanza un dado extra de @STR.",
	"ab_sword_en": "Roll an extra @STR die.",
	"ab_dage_name_es": "DAGA",
	"ab_dage_name_en": "DAGGER",
	"ab_dage_es": "Aplica -2HP directo a un enemigo.",
	"ab_dage_en": "Deal -2HP directly to an enemy.",
	"ab_crossbow_name_es": "BALLESTA",
	"ab_crossbow_name_en": "CROSSBOW",
	"ab_crossbow_es": "Aplica -4HP directo a un enemigo.",
	"ab_crossbow_en": "Deal -4HP directly to an enemy.",
	"ab_gold_ring_name_es": "ANILLO DORADO",
	"ab_gold_ring_name_en": "GOLDEN RING",
	"ab_gold_ring_es": "Otorga 3 de poder magico.",
	"ab_gold_ring_en": "Grants 3 magical power.",
	"ab_bread_name_es": "PAN DE VIAJE",
	"ab_bread_name_en": "TRAVEL BREAD",
	"ab_bread_es": "Sana +3HP.",
	"ab_bread_en": "Heal +3HP.",
	"ab_speed_bots_name_es": "BOTAS DE AGILIDAD",
	"ab_speed_bots_name_en": "AGILITY BOOTS",
	"ab_speed_bots_es": "Otorga un dado de @DEX.",
	"ab_speed_bots_en": "Grants one @DEX die.",
	"ab_rope_name_es": "CAPA",
	"ab_rope_name_en": "CLOAK",
	"ab_rope_es": "Otorga +2 de escudo y +1 a todos tus dados de destreza.",
	"ab_rope_en": "Gain +2 shield and +1 to all your dexterity dice.",
	"ab_iron_helm_name_es": "YELMO DE HIERRO",
	"ab_iron_helm_name_en": "IRON HELMET",
	"ab_iron_helm_es": "Otorga +5 de escudo.",
	"ab_iron_helm_en": "Grants +5 shield.",
	
	"def_tuto_rat_name_es": "Rata",
	"def_tuto_rat_name_en": "Rat",
	"def_rat_name_es": "Rata",
	"def_rat_name_en": "Rat",
	"def_bat_name_es": "Murcielago",
	"def_bat_name_en": "Bat",
	"def_goblin_name_es": "Trasgo",
	"def_goblin_name_en": "Goblin",
	"def_arrow_trap_name_es": "Trampa de Flechas",
	"def_arrow_trap_name_en": "Arrow Trap",
	"def_chest_name_es": "Cofre",
	"def_chest_name_en": "Chest",
	"def_slime_name_es": "Slime",
	"def_slime_name_en": "Slime",
	"def_ghost_name_es": "Espectro",
	"def_ghost_name_en": "Specter",
	"def_spider_name_es": "Aracnido",
	"def_spider_name_en": "Arachnid",
	"def_rune_trap_name_es": "Trampa Runica",
	"def_rune_trap_name_en": "Runic Trap",
	"def_skeleton_name_es": "Esqueleto",
	"def_skeleton_name_en": "Skeleton",
	"def_skeleton_king_name_es": "Rey no muerto",
	"def_skeleton_king_name_en": "Undead king",
	
	"def_ab_aggressive_name_es": "AGRESIVO",
	"def_ab_aggressive_name_en": "AGGRESSIVE",
	"def_ab_aggressive_es": "Te atacara al finalizar el turno causando entre -#1HP y -#2HP.",
	"def_ab_aggressive_en": "Will attack at the end of the turn causing between -#1HP and -#2HP.",
	"def_ab_counterattack_name_es": "CONTRATAQUE",
	"def_ab_counterattack_name_en": "COUNTERATTACK",
	"def_ab_counterattack_es": "Una vez por turno, cuando coloques un dado en esta carta recibes entre -#1HP y -#2HP",
	"def_ab_counterattack_en": "Once per turn, placing a die on this card deals -#1HP to -#2HP to you.",
	"def_ab_activation_name_es": "ACTIVACION",
	"def_ab_activation_name_en": "ACTIVATION",
	"def_ab_activation_es": "#0% de activartse al final del turno. Si no se activa, aumenta su probabilidad para el próximo turno.",
	"def_ab_activation_en": "#0% chance of activating at the end of turn. If not activate, its probability increases to next turn.",
	"def_ab_coveted_name_es": "CODICIADO",
	"def_ab_coveted_name_en": "COVETED",
	"def_ab_coveted_es": "#0% de perderse al final del turno. Si no se pierde, aumenta su probabilidad para el próximo turno.",
	"def_ab_coveted_en": "#0% chance of lost at the end of turn. If not lost, its probability increases to next turn.",	
	"def_ab_trap_damage_name_es": "DAÑO MASIVO",
	"def_ab_trap_damage_name_en": "MASSIVE DAMAGE",
	"def_ab_trap_damage_es": "Al activarse aplica entre -#1HP y -#2HP.",
	"def_ab_trap_damage_en": "Upon activation, deals between -#1HP and -#2HP.",
	"def_ab_shield_name_es": "ESCUDO",
	"def_ab_shield_name_en": "SHIELD",
	"def_ab_shield_es": "Reduce hasta #2 puntos el valor de cualquier dado de @STR colocado en esta carta. Se restablece al inicio de cada turno.",
	"def_ab_shield_en": "Reduces up to #2 from any @STR die placed on this card. Resets each turn.",
	"def_ab_drainer_name_es": "DRENADOR",
	"def_ab_drainer_name_en": "DRAINER",
	"def_ab_drainer_es": "Cada vez que te ataque con exito, recupera +#0HP.",
	"def_ab_drainer_en": "Each time it hits you, it regains +#0HP.",
	"def_ab_teasure_name_es": "TESORO",
	"def_ab_teasure_name_en": "TREASURE",
	"def_ab_teasure_es": "Al resolver esta carta obtendras un objeto.",
	"def_ab_teasure_en": "Gain an item when resolving this card.",
	"def_ab_necrotic_name_es": "NECROTICO",
	"def_ab_necrotic_name_en": "NECROTIC",
	"def_ab_necrotic_es": "Te atacara al finalizar el turno ignorando tu escudo entre -#1HP y -#2HP.",
	"def_ab_necrotic_en": "Attacks at end of turn ignoring your shield for -#1HP to -#2HP.",
	"def_ab_poison_name_es": "VENENO",
	"def_ab_poison_name_en": "POISON",
	"def_ab_poison_es": "Cada vez que te ataque con exito pierdes un punto de cordura.",
	"def_ab_poison_en": "Each hit also causes you to lose 1 sanity.",
	"def_ab_absorb_name_es": "ABSORBER",
	"def_ab_absorb_name_en": "ABSORB",
	"def_ab_absorb_es": "Absorbe el primer dado que apliques cada turno ignorando su valor.",
	"def_ab_absorb_en": "Absorbs the first die placed each turn, ignoring its value.",
	"def_ab_trap_sanity_name_es": "LOCURA",
	"def_ab_trap_sanity_name_en": "MADNESS",
	"def_ab_trap_sanity_es": "Al activarse reduce -#0 tu cordura.",
	"def_ab_trap_sanity_en": "Upon activation, reduces your sanity by -#0.",
	"def_ab_nigromant_name_es": "NIGROMANTE",
	"def_ab_nigromant_name_en": "NECROMANCER",
	"def_ab_nigromant_es": "Al final del turno, se cura +#0HP por cada esqueleto que haya en pie.",
	"def_ab_nigromant_en": "At the end of the turn, heal yourself for +#0HP for each skeleton still standing.",

	"destine_campfire_title_es":"Campamento",
	"destine_campfire_title_en":"Campfire",
	"destine_campfire_desc_es":"Tras explorar pasillos oscuros y sortear trampas oxidadas, tu grupo encuentra un respiro, una pequeña sala iluminada por brasas apagadas y el aroma tenue de hierbas quemadas. Alguien acampó aquí antes... pero ya no están.  Un círculo de piedras guarda las cenizas de una fogata, y un tronco musgoso invita a sentarse. Este es un lugar seguro, al menos por ahora. El aire es más templado, y el silencio no parece hostil.",
	"destine_campfire_desc_en":"After exploring dark corridors and avoiding rusty trapdoors, your group finds respite, a small room lit by dying embers and the faint scent of burning herbs. Someone camped here before... but they're gone now. A circle of stones holds the ashes of a campfire, and a mossy log invites you to sit. This is a safe place, at least for now. The air is milder, and the silence doesn't seem hostile.",
	"destine_campfire_op1_es":"Ganas 3 puntos de cordura.",
	"destine_campfire_op1_en":"You gain 3 sanity points.",
	"destine_campfire_op2_es":"Restaura hasta 7 HP.",
	"destine_campfire_op2_en":"Restores up to 7 HP.",
	"destine_campfire_op3_es":"Obtienes una racion de comida que rastaura 3 HP al final de cada combate durante 3 combates.",
	"destine_campfire_op3_en":"You gain a food ration that restores 3 HP at the end of each fight for 3 fights.",

	"destine_old_chest_title_es":"El viejo cofre",
	"destine_old_chest_title_en":"Campfire",
	"destine_old_chest_desc_es":"Tu y tu grupo entran en una peculiar habitación, la oscuridad parece más intensa, una niebla abrasiva se apodera de la sala y comienzan a escucharse susurros de otros tiempos. Un viejo cofre con insignias yace en la habitación.",
	"destine_old_chest_desc_en":"You and your party enter a peculiar room. The darkness seems to deepen, a scorching fog takes over, and whispers from another time begin to be heard. An old chest of insignia lies in the room.",
	"destine_old_chest_op1_es":"Continuar tu camino.",
	"destine_old_chest_op1_en":"",
	"destine_old_chest_op2_es":"Abrir el cofre, pierdes 3 puntos de cordura y ganas un objeto.",
	"destine_old_chest_op2_en":"Opening the chest, you lose 3 sanity points and gain an item.",

	"destine_end_level_title_es":"Expedicion completa",
	"destine_end_level_title_en":"Finish expedition",
	"destine_end_level_desc_es":"Muy bien aventureros! Han completado la expedicion!\nEs hora de volver a la taberna a descansar y contar tus logros!",
	"destine_end_level_desc_en":"All right, adventurers! You've completed the expedition!\nIt's time to head back to the tavern to rest and recount your accomplishments!",
	"destine_end_level_op1_es":"Vamos a la taberna.",
	"destine_end_level_op1_en":"Let's go to the tavern.",
	
	"destine_fail_level_title_es":"Abatidos",
	"destine_fail_level_title_en":"Dejected",
	"destine_fail_level_desc_es":"Este lugar es mas peligroso de lo que pensabas.\nReagrupate, descansa y vuelve a intentarlo.",
	"destine_fail_level_desc_en":"This place is more dangerous than you thought.\nRegroup, rest, and try again.",
	"destine_fail_level_op1_es":"Volvamos a la taberna.",
	"destine_fail_level_op1_en":"Let's go back to the tavern.",
	
	"tuto_welcome_es":"Bienvenidos aventureros! Les explicare las cosas basicas que todo aficionado deberia conocer antes de adentrarse en una mazmorra, hay muchos peligros alli.",
	"tuto_welcome_en":"Welcome, adventurers! I'll explain the basics every fan should know before entering a dungeon. There are many dangers there.",
	"tuto_party_es":"En la parte inferior veras las estadisticas de tu grupo. En cada turno lanzas un dado por cada punto de caracteristica que tengas.",
	"tuto_party_en":"At the bottom, you'll see your party's stats. Each turn, you roll a die for each stat point you have.",
	"tuto_dices_es":"Estos son tus dados para",
	"tuto_dices_en":"These are your dice for",
	"tuto_rat1_es":"Mira esa asquerosa rata! En la parte superior derecha veras sus @HP, debes reducirlos a cero para acabar con ella. Para eso toma tus dados y colocalos sobre ella.",
	"tuto_rat1_en":"Look at that disgusting rat! In the upper right corner, you'll see its @HP; you must reduce it to zero to kill it. To do this, take your dice and place them on it.",
	"tuto_rat2_es":"Pero cuidado, la rata tambien tiene estadisticas, que se descuentan al valor de los dados que apliques.",
	"tuto_rat2_en":"But beware, the rat also has statistics, which are discounted from the value of the dice you apply.",
	"tuto_rat3_es":"Ademas, todos los enemigos tienen habilidades, verifica que hace cada una antes de hacer tu jugada!",
	"tuto_rat3_en":"Also, all enemies have abilities, check what each one does before making your move!",
	"tuto_rat4_es":"Ahora si, elimina a esa rata de una vez..",
	"tuto_rat4_en":"Now, get rid of that rat once and for all.",
	"tuto_shield_es":"Casi lo olvido! Puedes usar dados para mitigar ataques colocandolos aqui! Si te sobran dados al final del turno se asignaran automaticamente.",
	"tuto_shield_en":"I almost forgot! You can use dice to mitigate attacks by placing them here! If you have any extra dice at the end of the turn, they'll be assigned automatically.",
	"tuto_good_work_es":"Buen trabajo! Ahora dejame mostrarte algunos trucos bajo la manga que te salvaran la vida mas de una vez.",
	"tuto_good_work_en":"Good job! Now let me show you some tricks up my sleeve that will save your life more than once.",
	"tuto_ability1_es":"Con este truco podras aumentar el valor de tus dados de @STR. Fundamental para no morir mordido por ratas!! jajaja!!",
	"tuto_ability1_en":"With this trick, you can increase the value of your @STR dice. Essential to avoid getting bitten by rats! Hahaha!",
	"tuto_power1_es":"Para usar habilidades como esta necesitas PODER!\n Hay muchas formas de conseguir poder, pero principalmente lo haras con tu foco de poder.",
	"tuto_power1_en":"To use abilities like this you need POWER!\nThere are many ways to gain power, but you will mainly do so with your power focus.",
	"tuto_power2_es":"Arroja algunos dados en tu foco y veras como se consigue el poder. Con eso podras usar tus habilidades.",
	"tuto_power2_en":"Roll some dice at your focus and you'll see how the power is gained. With that, you'll be able to use your abilities.",
	"tuto_end_es":"Bueno bueno.. Mis labios se secan de tanto hablar, me voy a la taberna..",
	"tuto_end_en":"Well well... My lips are dry from talking so much, I'm going to the tavern.",

	"tuto_tabern1_es":"Bien hecho, mereces un descanso en la taberna! Aqui podras reponerte y prepararte para tu proxima expedicion.",
	"tuto_tabern1_en":"Well done, you deserve a break at the tavern! Here you can recharge and prepare for your next expedition.",
	"tuto_tabern2_es":"Este es tu indicador de prestigio, cada vez que completes una expedicion aumentara tu reputacion!",
	"tuto_tabern2_en":"This is your prestige indicator, every time you complete an expedition your reputation will increase!",
	"tuto_tabern3_es":"Esa reputacion te servira para determinar cuantos objetos se te permitira llevar a tu proxima expedicion.",
	"tuto_tabern3_en":"That reputation will help you determine how many items you will be allowed to take on your next expedition.",
	"tuto_tabern4_es":"Siempre esta llegando gente nueva a la taberna, seguramente a algunos les gustaria ir contigo a las viejas ruinas.",
	"tuto_tabern4_en":"New people are always arriving at the tavern, surely some would like to go with you to the old ruins.",
	"tuto_tabern5_es":"Combina tu grupo de tres aventureros como mas te convenga, cada personaje aporta sus propios stats y habilidades al grupo.",
	"tuto_tabern5_en":"Combine your party of three adventurers as you see fit, each character bringing their own stats and abilities to the group.",
	"tuto_tabern6_es":"Cuendo estes listo, puedes viajar a la ruina por este sendero.",
	"tuto_tabern6_en":"When you're ready, you can travel to the ruin via this path.",
	"tuto_tabern7_es":"Muy bien!, Tengo mucho que limpiar alli atras, disfruta tu estadia!",
	"tuto_tabern7_en":"All right! I have a lot of cleaning to do back there, enjoy your stay!",
	
	"tuto_new_hero_es":"Un nuevo aventurero llego a la taberna.\nParece dispuesto a ayudarte en las ruinas.",
	"tuto_new_hero_en": "A new adventurer has arrived at the tavern. Seems ready to join your quest.",
	
	"tx_intro1_es":"Entrada del diario del Explorador Gerran Velmor,",
	"tx_intro1_en":"Log entry from Explorer Gerran Velmor,",
	"tx_intro2_es":"“Han pasado tres días desde que los pastores encontraron esa extraña entrada de piedra tras las rocas. No tardaron en llegar los rumores... y con ellos, los buscadores de fortuna. Yo fui uno de los primeros en entrar. Aunque solo eche un vistazo.”",
	"tx_intro2_en":"“Three days have passed since the shepherds found that strange stone entrance behind the rocks. It wasn't long before rumors began to spread... and with them, fortune seekers. I was one of the first to enter. Even if I only caught a glimpse.”",
	"tx_intro3_es":"“Las ruinas no son naturales. Los pasillos cambian. Las cámaras no están hechas por manos humanas… o al menos, no por manos de este tiempo. Hay símbolos que nadie ha podido traducir y ecos que parecen susurrar cuando uno se queda solo.”",
	"tx_intro3_en":"“The ruins are not natural. The corridors change. The chambers are not made by human hands… or at least, not by hands of this time. There are symbols that no one has been able to translate, and echoes that seem to whisper when one is alone.”",
	"tx_intro4_es":"“Intentare reunir un grupo. Tres aventureros dispuestos a desafiar la oscuridad por oro, poder… o redención. Les dare un mapa de como llegar, algunas provisiones, y pagare por la informacion, podria estar relacionado con las historias de mi Orden.”",
	"tx_intro4_en":"“I’ll try to gather a group. Three adventurers willing to challenge the darkness for gold, power… or redemption. I’ll give you a map, some supplies, and pay for the information. It might be related to the stories of my Order.”",
	"tx_intro5_es":"“Cada expedicion sera una nueva oportunidad. Cada descubrimiento, una soga tendida sobre el abismo. Los peligros rebosan la cueva y esas ruinas no parecen perdonar la imprudencia.”",
	"tx_intro5_en":"“Each expedition will be a new opportunity. Each discovery, a rope stretched across the abyss. Dangers abound in the cave, and these ruins don't seem to forgive recklessness.”",
	"tx_intro6_es":"– Gerran Velmor, Explorador de la Orden del Ojo Silente",
	"tx_intro6_en":"– Gerran Velmor, Scout of the Order of the Silent Eye",
	
	"tx_sanity_es":"Tu nivel de cordura baja en cada turno, recuperaras parte de ella al superar cada habitacion. Ten cuidado, si llegas a cero los espectros de la ruina vendran por ti!",
	"tx_sanity_en": "Your sanity level decreases with each turn, and you'll regain some of it as you clear each room. Be careful, if you reach zero, the specters of ruin will come for you!",
	
	"all_party_stats_es":"@PARTY_STR  @PARTY_DEX  @PARTY_MAG",
	"all_party_stats_en":"@PARTY_STR  @PARTY_DEX  @PARTY_MAG",
	"info_dungeon_level_es":"EXPEDICION #0    SALON #1/#2",
	"info_dungeon_level_en": "EXPEDITION #0    ROOM #1/#2",
	"some_stats_es":"[color="+DiceManager.COLORS["S"]+"]@STR:#0[/color]  [color="+DiceManager.COLORS["D"]+"]@DEX:#1[/color]  [color="+DiceManager.COLORS["M"]+"]@MAG:#2[/color]",
	"some_stats_en":"[color="+DiceManager.COLORS["S"]+"]@STR:#0[/color]  [color="+DiceManager.COLORS["D"]+"]@DEX:#1[/color]  [color="+DiceManager.COLORS["M"]+"]@MAG:#2[/color]",
	
	"rogue_es": "picaro",
	"rogue_en": "rogue",
	"sorcerer_es": "hechicero",
	"sorcerer_en": "sorcerer",
	"explorer_es": "explorador",
	"explorer_en": "explorer",
	"barbarian_es": "barbaro",
	"barbarian_en": "barbarian",
	"warrior_es": "guerrero",
	"warrior_en": "warrior",
	
	"stat_S_es": "Fuerza",
	"stat_S_en": "Strength",
	"stat_D_es": "Destreza",
	"stat_D_en": "Dexterity",
	"stat_M_es": "Magia",
	"stat_M_en": "Magic",
	"stat_hp_es": "Vitalidad",
	"stat_hp_en": "Vitality",
	"stat_sanity_es": "Cordura",
	"stat_sanity_en": "Sanity",
	"max_power_es": "Carga maxima",
	"max_power_en": "Max charge",
	"attack_miss_es": "Falla",
	"attack_miss_en": "Miss",
	"fatigued_es": "Cansado",
	"fatigued_en": "Tired",
	"fatigued_desc_es": "no podrás usar sus habilidades",
	"fatigued_desc_en": "you won't be able to use their abilities",
	
	"prestige_info_es": "PRESTIGIO: es el reconocimiento de tu grupo e indica cuantos objetos puedes llevar a tu próxima expedición."
}

var REPLACES = {
	"@STR_es" = "[color="+DiceManager.COLORS["S"]+"]Fuerza[/color]",
	"@STR_en" = "[color="+DiceManager.COLORS["S"]+"]Strength[/color]",
	"@DEX_es" = "[color="+DiceManager.COLORS["D"]+"]Destreza[/color]",
	"@DEX_en" = "[color="+DiceManager.COLORS["D"]+"]Dexterity[/color]",
	"@MAG_es" = "[color="+DiceManager.COLORS["M"]+"]Magia[/color]",
	"@MAG_en" = "[color="+DiceManager.COLORS["M"]+"]Magic[/color]",
	"@HP" = "[color=ff0000]HP[/color]",
}

func set_text_vars(vars):
	text_vars = vars

func get_text(code,styles=[]):
	code += "_"+current_lang
	if !code in TEXTS: return code
	var text = TEXTS[code]
	for k in REPLACES.keys(): 
		var fk = k.replace("_"+current_lang,"")
		text = text.replace(fk,REPLACES[k])
	for i in text_vars.size():
		text = text.replace("#"+str(i),str(text_vars[i]))
	if "UPPER" in styles: text = text.to_upper()
	if "TITLE" in styles: text = "[color=f0f050]"+text+"[/color]"
	return text

func get_req_string(req={}):
	var result = ""
	for k in req.keys():
		var c = DiceManager.COLORS[k]
		if k in req: for i in req[k]: result += "[img=14 color="+c+"]res://assets/full_white_point.png[/img]" 
	return result

func has_key(code):
	code += "_"+current_lang
	return (code in TEXTS)
